version: "3"
services:
  selenium:
    image: selenium/hub
    ports:
      - "4444:4444"
  firefoxnode:
      image: selenium/node-firefox
      environment:
        - HUB_PORT_4444_TCP_ADDR=selenium
        - HUB_PORT_4444_TCP_PORT=4444
      ports:
        - "5555"
      depends_on:
        - selenium
  chromenode:
      image: selenium/node-chrome
      environment:
        - HUB_PORT_4444_TCP_ADDR=selenium
        - HUB_PORT_4444_TCP_PORT=4444
      ports:
        - "5555"
      depends_on:
        - selenium
networks:
  default: